### ISSUE TITLE
Photo grid on home page isn't showing

### ISSUE THREAD

**Issue by ckollars** [thenewblk/maverick_mayhem#33]
This is happening in IE9. Looking at the console it's saying it's because it doesn't support `matchMedia`.

![screen shot 2015-02-24 at 12 37 42 pm](https://cloud.githubusercontent.com/assets/599651/6356315/3593d29a-bc22-11e4-8966-a633a5c9a65d.png)

**Comment by bangarang** [comment]
Looks like we need to add a polyfill a la http://wicky.nillia.ms/enquire.js/#legacy-browsers 

This one is recommended: https://github.com/paulirish/matchMedia.js
