### ISSUE TITLE
Add signup form for a newsletter

### ISSUE THREAD

**Issue by ckollars** [thenewblk/maverick_mayhem#8]

**Comment by mattlinder** [comment]
Would you like me to set up a campaign monitor account?

**Comment by mattlinder** [comment]
We need to sort out what lists we want to subscribe people to.

**Comment by ckollars** [comment]
@mattlinder we will need this so go ahead and create one when you have the details sorted out.

**Comment by ckollars** [comment]
Join: Get news, updates, and special offers 
Form fields: Name, Email

Need to get Campaign Monitor set up. Would like to add an automatic email that goes out after you sign up with a welcome message and a link to a survey to get more demographic info and interests (hockey, basketball, etc.).

**Comment by ckollars** [comment]
added
